/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'style-templates': StyleTemplate;
    'model-configs': ModelConfig;
    tasks: Task;
    'sub-tasks': SubTask;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'style-templates': StyleTemplatesSelect<false> | StyleTemplatesSelect<true>;
    'model-configs': ModelConfigsSelect<false> | ModelConfigsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    'sub-tasks': SubTasksSelect<false> | SubTasksSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      'expand-prompt': TaskExpandPrompt;
      'generate-image': TaskGenerateImage;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Generated images and videos
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alt text for accessibility
   */
  alt: string;
  /**
   * Source SubTask reference
   */
  relatedSubtask?: (string | null) | SubTask;
  /**
   * Asset type (image or video)
   */
  assetType?: ('image' | 'video') | null;
  /**
   * Generation parameters snapshot
   */
  generationMeta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Parent task ID for quick filtering
   */
  taskId?: string | null;
  /**
   * Style ID for quick filtering
   */
  styleId?: string | null;
  /**
   * Model ID for quick filtering
   */
  modelId?: string | null;
  /**
   * Subject slug for quick filtering
   */
  subjectSlug?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Individual image generation sub-tasks
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-tasks".
 */
export interface SubTask {
  id: string;
  /**
   * Reference to parent Task
   */
  parentTask: string | Task;
  /**
   * Execution status
   */
  status: 'pending' | 'processing' | 'success' | 'failed';
  /**
   * Current worker ID (lock mechanism)
   */
  lockedBy?: string | null;
  /**
   * Lock expiration time
   */
  lockExpiresAt?: string | null;
  /**
   * Applied style template ID
   */
  styleId: string;
  /**
   * Target AI model ID
   */
  modelId: string;
  /**
   * Prompt variant details (variantId, variantName, expandedPrompt, subjectSlug)
   */
  expandedPrompt:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Merged prompt (expanded prompt + style modifiers)
   */
  finalPrompt: string;
  /**
   * Negative prompt from style template
   */
  negativePrompt?: string | null;
  /**
   * Index within batch (0-based)
   */
  batchIndex: number;
  /**
   * Aspect ratio for generation
   */
  aspectRatio?: ('1:1' | '16:9' | '9:16' | '4:3' | '3:4') | null;
  /**
   * Optional seed for reproducibility
   */
  seed?: number | null;
  /**
   * Raw API request body (schema-less)
   */
  requestPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Raw API response (schema-less)
   */
  responseData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Error message/stack trace
   */
  errorLog?: string | null;
  /**
   * Normalized error type
   */
  errorCategory?:
    | (
        | 'RATE_LIMITED'
        | 'CONTENT_FILTERED'
        | 'INVALID_INPUT'
        | 'PROVIDER_ERROR'
        | 'NETWORK_ERROR'
        | 'TIMEOUT'
        | 'UNKNOWN'
      )
    | null;
  /**
   * Number of retry attempts (max: 3)
   */
  retryCount: number;
  /**
   * Processing start time
   */
  startedAt?: string | null;
  /**
   * Processing completion time
   */
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI image generation tasks
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: string;
  /**
   * User's original subject input
   */
  subject: string;
  /**
   * LLM-optimized prompt variants
   */
  expandedPrompts?:
    | {
        variantId: string;
        /**
         * e.g., "Realistic", "Abstract", "Artistic"
         */
        variantName: string;
        originalPrompt: string;
        expandedPrompt: string;
        /**
         * English slug for file naming
         */
        subjectSlug: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Selected style templates from database (legacy - use importedStyleIds for JSON styles)
   */
  styles?: (string | StyleTemplate)[] | null;
  /**
   * Select style templates from imported JSON styles
   */
  importedStyleIds?:
    | (
        | 'base'
        | '3d-model'
        | 'abstract'
        | 'abstract-expressionism'
        | 'abstract-expressionism-2'
        | 'academia'
        | 'action-figure'
        | 'adorable-3d-character'
        | 'adorable-kawaii'
        | 'ads-advertising'
        | 'ads-automotive'
        | 'ads-corporate'
        | 'ads-fashion-editorial'
        | 'ads-food-photography'
        | 'ads-gourmet-food-photography'
        | 'ads-luxury'
        | 'ads-real-estate'
        | 'ads-retail'
        | 'advertising'
        | 'alien'
        | 'analog-film'
        | 'anime'
        | 'architectural'
        | 'art-deco'
        | 'art-deco-2'
        | 'art-nouveau'
        | 'art-nouveau-2'
        | 'astral-aura'
        | 'avant-garde'
        | 'baroque'
        | 'bauhaus-style-poster'
        | 'biomechanical'
        | 'biomechanical-cyberpunk'
        | 'blueprint-schematic-drawing'
        | 'bubble-bobble-game'
        | 'caricature'
        | 'cel-shaded-art'
        | 'character-design-sheet'
        | 'cinematic-film'
        | 'cinematic-photograph'
        | 'classicism-art'
        | 'collage'
        | 'color-field-painting'
        | 'colored-pencil-art'
        | 'comic-book'
        | 'commercial-illustration-1920s'
        | 'conceptual-art'
        | 'constructivism-1'
        | 'constructivism-2'
        | 'craft-clay'
        | 'cubism-1'
        | 'cubism-2'
        | 'cybernetic'
        | 'cybernetic-robot'
        | 'cyberpunk'
        | 'cyberpunk-cityscape'
        | 'dadaism'
        | 'dark-fantasy'
        | 'dark-moody-atmosphere'
        | 'digital-art'
        | 'disco'
        | 'dmt-art-style'
        | 'doodle-art'
        | 'double-exposure'
        | 'dreamscape'
        | 'dripping-paint-splatter-art'
        | 'dystopian'
        | 'enhance'
        | 'expressionism-1'
        | 'expressionism-2'
        | 'faded-polaroid-photo'
        | 'fairy-tale'
        | 'fantasy-art'
        | 'fauvism'
        | 'fighting-game'
        | 'film-noir'
        | 'flat-2d-art'
        | 'flat-papercut'
        | 'food-photography'
        | 'fortnite-art-style'
        | 'futurism'
        | 'futuristic'
        | 'futuristic-sci-fi'
        | 'glamour'
        | 'glitchcore'
        | 'glo-fi'
        | 'googie-art-style'
        | 'gothic'
        | 'graffiti-art-1'
        | 'graffiti-art-2'
        | 'grunge'
        | 'gta'
        | 'harlem-renaissance-art'
        | 'hdr'
        | 'high-fashion'
        | 'horror'
        | 'hyperrealism'
        | 'idyllic'
        | 'impressionism-1'
        | 'impressionism-2'
        | 'infographic-drawing'
        | 'ink-dripping-drawing'
        | 'isometric-style'
        | 'japanese-ink-drawing'
        | 'kawaii'
        | 'kirigami'
        | 'knolling-photography'
        | 'legend-of-zelda'
        | 'light-cheery-atmosphere'
        | 'line-art'
        | 'logo-design'
        | 'long-exposure'
        | 'lovecraftian-horror'
        | 'lowpoly'
        | 'luxurious-elegance'
        | 'macabre'
        | 'macro-photography'
        | 'mandala-art'
        | 'manga'
        | 'marker-drawing'
        | 'medievalism'
        | 'metropolis'
        | 'minecraft'
        | 'minimalism-1'
        | 'minimalism-2'
        | 'monochrome'
        | 'nautical'
        | 'neo-baroque'
        | 'neo-byzantine'
        | 'neo-futurism'
        | 'neo-impressionism'
        | 'neo-rococo'
        | 'neoclassicism'
        | 'neon-noir'
        | 'neon-punk'
        | 'op-art'
        | 'origami'
        | 'ornate-and-intricate'
        | 'paper-mache'
        | 'paper-quilling'
        | 'papercut-collage'
        | 'papercut-shadow-box'
        | 'pencil-sketch'
        | 'photographic'
        | 'pixel-art'
        | 'pointillism'
        | 'pok-mon'
        | 'pop-art-1'
        | 'pop-art-2'
        | 'psychedelic'
        | 'real-estate-photography'
        | 'renaissance'
        | 'retro-arcade'
        | 'retro-cyberpunk'
        | 'retro-futurism'
        | 'retro-game'
        | 'rococo'
        | 'rpg-fantasy'
        | 'silhouette'
        | 'silhouette-art'
        | 'simple-vector-art'
        | 'sketchup'
        | 'space'
        | 'stacked-papercut'
        | 'stained-glass'
        | 'steampunk-1'
        | 'steampunk-2'
        | 'sticker-designs'
        | 'strategy-game'
        | 'street-fighter'
        | 'super-mario'
        | 'suprematism'
        | 'surrealism-1'
        | 'surrealism-2'
        | 'techwear-fashion'
        | 'terragen'
        | 'texture'
        | 'thick-layered-papercut'
        | 'tilt-shift-photo'
        | 'tranquil-relaxing-atmosphere'
        | 'tribal'
        | 'typography'
        | 'vaporwave'
        | 'vibrant-rim-light'
        | 'volumetric-lighting'
        | 'watercolor-1'
        | 'watercolor-2'
        | 'whimsical-and-playful'
        | 'wild-west'
        | 'zentangle'
      )[]
    | null;
  /**
   * Selected AI model IDs
   */
  models: ('flux-pro' | 'flux-dev' | 'flux-schnell' | 'dalle-3' | 'imagen-3')[];
  /**
   * Batch generation settings
   */
  batchConfig: {
    /**
     * Images per prompt variant (1-50)
     */
    countPerPrompt: number;
    /**
     * Computed: prompts × styles × models × countPerPrompt
     */
    totalExpected?: number | null;
    /**
     * Number of prompt variants to generate (1-10)
     */
    variantCount?: number | null;
    /**
     * Include Base style (no modifications) in generation
     */
    includeBaseStyle?: boolean | null;
  };
  /**
   * Current task status
   */
  status: 'draft' | 'queued' | 'expanding' | 'processing' | 'completed' | 'partial_failed' | 'failed';
  /**
   * Completion percentage (0-100)
   */
  progress: number;
  /**
   * Enable web search (RAG) for prompt optimization
   */
  webSearchEnabled?: boolean | null;
  /**
   * Aspect ratio for generated images
   */
  aspectRatio?: ('1:1' | '16:9' | '9:16' | '4:3' | '3:4') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable style templates for AI image generation
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "style-templates".
 */
export interface StyleTemplate {
  id: string;
  /**
   * Unique identifier (lowercase, hyphens only)
   */
  styleId: string;
  /**
   * Display name for the style
   */
  name: string;
  /**
   * Brief description of the style effect
   */
  description?: string | null;
  /**
   * Positive prompt template. Must contain {prompt} placeholder.
   */
  positivePrompt: string;
  /**
   * Negative prompt additions (appended to any user negative prompt)
   */
  negativePrompt?: string | null;
  /**
   * Preview thumbnail showing the style effect
   */
  previewImage?: (string | null) | Media;
  /**
   * System styles cannot be deleted
   */
  isSystem?: boolean | null;
  /**
   * Display order in UI (lower = first)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * AI model configurations and rate limits
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-configs".
 */
export interface ModelConfig {
  id: string;
  /**
   * Unique identifier (e.g., flux-pro, dalle-3)
   */
  modelId: string;
  /**
   * Human-readable name
   */
  displayName: string;
  /**
   * AI provider for this model
   */
  provider: 'fal' | 'openai' | 'google';
  /**
   * Whether this model is available for selection
   */
  isEnabled?: boolean | null;
  /**
   * Maximum concurrent requests
   */
  rateLimit: number;
  /**
   * Default generation parameters (JSON)
   */
  defaultParams:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Supported aspect ratios for this model
   */
  supportedAspectRatios: ('1:1' | '16:9' | '9:16' | '4:3' | '3:4')[];
  /**
   * Features supported by this model
   */
  supportedFeatures?: ('batch' | 'seed' | 'negativePrompt')[] | null;
  /**
   * Display order in UI
   */
  sortOrder?: number | null;
  /**
   * Internal notes about this model
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'expand-prompt' | 'generate-image';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'expand-prompt' | 'generate-image') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'style-templates';
        value: string | StyleTemplate;
      } | null)
    | ({
        relationTo: 'model-configs';
        value: string | ModelConfig;
      } | null)
    | ({
        relationTo: 'tasks';
        value: string | Task;
      } | null)
    | ({
        relationTo: 'sub-tasks';
        value: string | SubTask;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  relatedSubtask?: T;
  assetType?: T;
  generationMeta?: T;
  taskId?: T;
  styleId?: T;
  modelId?: T;
  subjectSlug?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "style-templates_select".
 */
export interface StyleTemplatesSelect<T extends boolean = true> {
  styleId?: T;
  name?: T;
  description?: T;
  positivePrompt?: T;
  negativePrompt?: T;
  previewImage?: T;
  isSystem?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "model-configs_select".
 */
export interface ModelConfigsSelect<T extends boolean = true> {
  modelId?: T;
  displayName?: T;
  provider?: T;
  isEnabled?: T;
  rateLimit?: T;
  defaultParams?: T;
  supportedAspectRatios?: T;
  supportedFeatures?: T;
  sortOrder?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  subject?: T;
  expandedPrompts?:
    | T
    | {
        variantId?: T;
        variantName?: T;
        originalPrompt?: T;
        expandedPrompt?: T;
        subjectSlug?: T;
        id?: T;
      };
  styles?: T;
  importedStyleIds?: T;
  models?: T;
  batchConfig?:
    | T
    | {
        countPerPrompt?: T;
        totalExpected?: T;
        variantCount?: T;
        includeBaseStyle?: T;
      };
  status?: T;
  progress?: T;
  webSearchEnabled?: T;
  aspectRatio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-tasks_select".
 */
export interface SubTasksSelect<T extends boolean = true> {
  parentTask?: T;
  status?: T;
  lockedBy?: T;
  lockExpiresAt?: T;
  styleId?: T;
  modelId?: T;
  expandedPrompt?: T;
  finalPrompt?: T;
  negativePrompt?: T;
  batchIndex?: T;
  aspectRatio?: T;
  seed?: T;
  requestPayload?: T;
  responseData?: T;
  errorLog?: T;
  errorCategory?: T;
  retryCount?: T;
  startedAt?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskExpand-prompt".
 */
export interface TaskExpandPrompt {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerate-image".
 */
export interface TaskGenerateImage {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}